### ISSUE TITLE
Tag delete failure

### ISSUE THREAD

**Issue by drinkingChai** [drinkingChai/professional-website#2]
Detected on the API

`  Delete tag
TypeError: Cannot convert undefined or null to object
    at Object.module.exports.delete (C:\Users\wzaman\Documents\GitHub\professional-website\models\tags.js:56:32)
    at C:\Users\wzaman\Documents\GitHub\professional-website\routes\tags.js:20:15`

**Comment by drinkingChai** [comment]
Fixed in a2ea78aa52450ce96b28818cce2fca19881c9ea5
